language: cpp
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
dist: trusty


script: "make pcst_fast_test && ./pcst_fast_test"

notifications:
  recipients:
    - ludwigschmidt2@gmail.com
  email:
    on_success: never
    on_failure: change
